substitutions:
  devicename: home-center

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pw
  fast_connect: true
  ap:
    ssid: ${devicename}
    password: !secret ap_pw
# captive_portal:
# web_server:
#   port: !secret web_port
#   auth:
#     username: !secret web_user
#     password: !secret web_pw
api:
  password: !secret api_pw
ota:
  password: !secret ota_pw

logger:
  level: INFO

esphome:
  name: ${devicename}
  platform: ESP32
  board: esp-wrover-kit


esp32_ble_tracker:
  scan_parameters:
    interval: 320ms
    window: 160ms
    

light:
  - platform: binary
    name: "LEDonBoard"
    output: light_output

output:
  - id: light_output
    platform: gpio
    inverted: True
    pin: GPIO23

sensor:
  - platform: xiaomi_cgg1
    mac_address: "58:2D:34:10:41:3B"
    temperature:
      name: "CGG1 Temperature"
    humidity:
      name: "CGG1 Humidity"
      icon: mdi:water-percent
    battery_level:
      name: "CGG1 Battery"
      icon: mdi:battery-80

  - platform: xiaomi_miscale2
    mac_address: '5C:CA:D3:5D:A1:C6'
    weight:
      name: "Scale Weight"
      id: weight_miscale
      on_value:
        then:
          - lambda: |-
              if (id(weight_miscale).state >= 60 && id(weight_miscale).state < 80) {
                return id(weight_kay).publish_state(x);}
              else if (id(weight_miscale).state >= 40 && id(weight_miscale).state < 60) {
                return id(weight_ruby).publish_state(x);}
    impedance:
      name: "Scale Impedance"
      id: impedance_xiaomi
      on_value:
        then:
          - lambda: |-
              if (id(weight_miscale).state >= 60 && id(weight_miscale).state < 80) {
                return id(impedance_kay).publish_state(x);}
              else if (id(weight_miscale).state >= 40 && id(weight_miscale).state < 60) {
                return id(impedance_ruby).publish_state(x);}
  - platform: template
    name: Weight Kay
    id: weight_kay
    unit_of_measurement: 'kg'
    icon: mdi:weight-kilogram
    accuracy_decimals: 2
  - platform: template
    name: Impedance Kay
    id: impedance_kay
    unit_of_measurement: 'ohm'
    icon: mdi:omega
    accuracy_decimals: 0
  - platform: template
    name: Weight Ruby
    id: weight_ruby
    unit_of_measurement: 'kg'
    icon: mdi:weight-kilogram
    accuracy_decimals: 2
  - platform: template
    name: Impedance Ruby
    id: impedance_ruby
    unit_of_measurement: 'ohm'
    icon: mdi:omega
    accuracy_decimals: 0

