substitutions:
  devicename: sonoff04

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pw
  fast_connect: true
  ap:
    ssid: ${devicename}
    password: !secret ap_pw
captive_portal:
web_server:
  port: !secret web_port
  auth:
    username: !secret web_user
    password: !secret web_pw
api:
  password: !secret api_pw
ota:
  password: !secret ota_pw

logger:
  baud_rate: 0

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "按钮"
    on_press:
      - switch.toggle: relay
      
switch:
  - platform: gpio
    name: "继电器"
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_ON

status_led:
  pin:
    number: GPIO13
    inverted: yes

uart:
  rx_pin: RX
  tx_pin: TX
  baud_rate: 9600

modbus:

sensor:
  - platform: pzemac
    current:
      name: "current"
    voltage:
      name: "voltage"
    energy:
      name: "energy"
      filters:
        - lambda: return x/1000;
      unit_of_measurement: "kWh"
      state_class: "measurement"
      device_class: "energy"
      accuracy_decimals: 5
    power:
      name: "power"
    frequency:
      name: "frequency"
    power_factor:
      name: "powerFactor"
    update_interval: 5s

